# your-gitops-repo/rabbitmq-minimal/rabbitmq-cluster-cr.yaml

apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: fleet-mq-cluster
  namespace: rabbitmq-system # Must be the same as the Operator's namespace
spec:
  # 1. Single Replica Configuration
  replicas: 1 
  
  # 2. No Storage/Persistence Configuration
  # The 'storage: 0Gi' value is used to explicitly disable persistence
  # for the StatefulSet managed by the Operator.
  persistence:
    storageClassName: "" # Ensure this is empty/not set if persistence is disabled
  
    
