# templates/02_rabbitmq-user.yaml
{{- if or (not .Values.existingPerm) (not .Values.permHasHook) }}
apiVersion: rabbitmq.com/v1beta1
kind: User
metadata:
  name: fleet-provisioned-user
  namespace: rabbitmq-system
  annotations:
    # 1. Hook Phase: Run after installation
    "helm.sh/resource-policy": "keep"
    "meta.helm.sh/release-name": rabbitmq-cluster
    "meta.helm.sh/release-namespace": rabbitmq-system
  # The namespace will be overridden by the targetCustomizations setting: rabbitmq-app
spec:
  tags:
    - administrator
    - management
    
  # Link this user to the cluster deployed above
  rabbitmqClusterReference:
    name: fleet-mq-cluster
    namespace: rabbitmq-cluster
{{- end }}
